name: Alerta CI Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar c贸digo del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: |
          node index.js

      - name: Enviar notificaci贸n a ntfy
        run: |
          curl -X POST ^
            -H "X-Title: Push a main detectado" ^
            -d "Se subi贸 c贸digo al repositorio ${{ github.repository }} por ${{ github.actor }}" ^
            https://ntfy.sh/devops-itla
